#!groovy

// Generated by IBM TransformationAdvisor
// Fri Feb 22 03:11:42 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}